/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anagramchecker;

import static anagramchecker.App.isAnagram;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class AppTest {

  @Test
  void testIsAnagram() {
    assertTrue(isAnagram("simpleAnagram1.txt", "simpleAnagram2.txt"));
    assertTrue(isAnagram("diffCasesAnagram1.txt", "diffCasesAnagram2.txt"));
    assertTrue(isAnagram("extraSpaceAnagram1.txt", "extraSpaceAnagram2.txt"));
    assertTrue(isAnagram("umlautAnagram1.txt", "umlautAnagram2.txt"));
    assertTrue(isAnagram("emptyAnagram1.txt", "emptyAnagram2.txt"));
    assertTrue(isAnagram("whitespacesAnagram1.txt", "whitespacesAnagram2.txt"));
    assertTrue(isAnagram("1MbAnagram1.txt", "1MbAnagram2.txt"));
    assertFalse(isAnagram("notAnagram1.txt", "notAnagram2.txt"));
  }
}
